### ISSUE TITLE
Exporting logs to elasticsearch

### ISSUE THREAD

**Issue by guisfits** [open-telemetry/opentelemetry-erlang#401]
Hello, 

I'm trying to send the application logs to elasticsearch. I'm following the [getting started tutorial](https://opentelemetry.io/docs/instrumentation/erlang/getting-started/). 
To trace I'm using [otlp/elastic](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/elasticexporter) and works fine. To logs I'm using [elasticsearch](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/elasticsearchexporter) exporter, and it isn't working. 

my `otel-collector-config.yml`
```yml
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  otlp/elastic: 
    endpoint: "apm:8200"
    tls:
      insecure: true

  elasticsearch:
    index: "core.darkwing"
    endpoints: ["elasticsearch:9200"]
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/elastic]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/elastic]
    logs: 
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch, otlp/elastic]
````

I'm running on docker-compose
```yml
 ...
 elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic
   
  apm:
    image: docker.elastic.co/apm/apm-server:7.13.2
    networks:
      - elastic
    ports:
      - "8200:8200"
    command: >
      apm-server -e
               -E apm-server.rum.enabled=true
               -E setup.kibana.host=kibana:5601
               -E setup.template.settings.index.number_of_replicas=0
               -E apm-server.kibana.enabled=true
               -E apm-server.kibana.host=kibana:5601
               -E output.elasticsearch.hosts=["elasticsearch:9200"]
    depends_on:
      - elasticsearch
      - kibana

  otel:
    image: otel/opentelemetry-collector-contrib-dev:latest
    command: ["--config=/etc/otel/config.yaml"]
    privileged: true
    ports:
      - "4317:4317" #grpc
      - "4318:4318" #http
    volumes:
      - ./otel-collector-config.yaml:/etc/otel/config.yaml
    depends_on:
      - elasticsearch
      - apm
    networks:
      - elastic
    links:
      - apm
      - elasticsearch
   ...
```

It looks like the logs are not arriving in the collector. The [opentelemetry](https://hex.pm/packages/opentelemetry) sdk for Elixir, gets the logs from [Logger](https://hexdocs.pm/logger/1.12.3/Logger.html) and send to collector automatically? Has some specific  configuration that's need to do? I didn't find any example to export logs with open-telemetry and Elixir. 

I'll be grateful for any help.
Thanks
