### ISSUE TITLE
Update semconv scripts to support extended stability levels

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/opentelemetry-erlang#823]
Erlang uses exact match for stability
https://github.com/open-telemetry/opentelemetry-erlang/blob/1a8bb51daf6813ddf7041a15001c13266f6b29b3/apps/opentelemetry_semantic_conventions/makefile#L38

It works great for stable level, but we're adopting other levels (https://github.com/open-telemetry/semantic-conventions/issues/1096) and starting to use `development`, `rc`.

You can either leverage new [`semconv_grouped_attributes`](https://github.com/open-telemetry/weaver/blob/b985fd3e742f9258444ef89b70831961bc3ef0a8/crates/weaver_forge/README.md#jq-filters) helper in weaver 

(e.g. here's how [Java uses it](https://github.com/open-telemetry/semantic-conventions-java/blob/6847d78f1396b06336cb6d2a4e8eaac10f4c4c2d/buildscripts/templates/registry/java/weaver.yaml#L24

))
```yaml
  - pattern: SemanticAttributes.java.j2
    filter: >
      semconv_grouped_attributes({
        "exclude_root_namespace": $excluded_namespaces,
        "exclude_stability": ["experimental"] # experimental here is fine, weaver matches all non-stable things to it
      }) | map({
          root_namespace: .root_namespace,
          attributes: .attributes,
          excluded_attributes: $excluded_attributes
      })
```

or replace logic inside https://github.com/open-telemetry/opentelemetry-erlang/blob/1a8bb51daf6813ddf7041a15001c13266f6b29b3/apps/opentelemetry_semantic_conventions/templates/registry/erlang/semantic_attributes.hrl.j2#L18 to cover other stability levels.

E.g. you might find weaver [`experimental` and other similar helpers](https://github.com/open-telemetry/weaver/blob/b985fd3e742f9258444ef89b70831961bc3ef0a8/crates/weaver_forge/README.md#jinja-tests-reference) useful.

```j2
{% if attribute is experimental %}
...
{% if attribute is stable%}
``
